### ISSUE TITLE
Error getting Projections

### ISSUE THREAD

**Issue by alexnorton111** [blue-shoes/ottoneu-toolbox#45]
I have been unable to download the projections: Log message

023-01-28 18:19:02,646 WDM INFO ====== WebDriver manager ======
2023-01-28 18:19:02,999 WDM INFO Current google-chrome version is 109.0.5414
2023-01-28 18:19:02,999 WDM INFO Get LATEST chromedriver version for 109.0.5414 google-chrome
2023-01-28 18:19:03,067 WDM INFO Driver [C:\Users\alex\.wdm\drivers\chromedriver\win32\109.0.5414.74\chromedriver.exe] found in cache
2023-01-28 18:19:30,064 root ERROR Error retrieving projections
Traceback (most recent call last):
  File "ui\dialog\wizard\projection_import.py", line 197, in validate
  File "services\projection_services.py", line 415, in create_projection_from_download
  File "services\projection_services.py", line 25, in download_projections
  File "scrape\scrape_fg.py", line 54, in getProjectionDataset
  File "scrape\scrape_base.py", line 39, in getDataset
  File "scrape\scrape_base.py", line 52, in getDatasetFromDownloads

Then i tried to export the projections and upload them using the Custom option but that did not work . Here is the error message

2023-01-28 19:01:44,033 root ERROR Error retrieving projections
Traceback (most recent call last):
  File "ui\dialog\wizard\projection_import.py", line 201, in validate
  File "services\projection_services.py", line 178, in create_projection_from_upload
  File "pandas\util\_decorators.py", line 311, in wrapper
  File "pandas\io\parsers\readers.py", line 680, in read_csv
  File "pandas\io\parsers\readers.py", line 575, in _read
  File "pandas\io\parsers\readers.py", line 934, in __init__
  File "pandas\io\parsers\readers.py", line 1218, in _make_engine
  File "pandas\io\common.py", line 786, in get_handle
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\alex'

**Comment by blue-shoes** [comment]
I have had other people with this automatic download issue as well that I will need to investigate. In the meantime for the manual export/upload, please use the 1.1.1-beta release that fixes an error introduced when projection datasets from FanGraphs had additional columns added.

**Comment by alexnorton111** [comment]
Confirmed the Beta loaded . Thx

**Comment by alexnorton111** [comment]
Got the points projections going however when i try to generate values  th e progress bar goes green to about 20% but does not move after that. 
Only one line in the log:
2023-01-28 19:57:44,626 root WARNING Input errors

**Comment by blue-shoes** [comment]
That log line appears unrelated. Can you tell me what inputs you used to perform calculations so I can try to reproduce this, including which projections you downloaded? I will try to look into this as soon as possible.

**Comment by blue-shoes** [comment]
For the automatic downloads, there appears to be an issue when using Chrome or Edge that I am having trouble nailing down. It currently works with Firefox. If Firefox is installed on the computer, you can set the Toolbox to use it via Menu -> Preferences

**Comment by blue-shoes** [comment]
A functional fix for this is available in the 1.1.1-beta2 release. Chrome and Edge downloads are not done headlessly (i.e. not in the background), but are functional now
